import styles from '../styles/components/Header.module.scss'
import Link from 'next/link'
import {useRouter }from 'next/router'
import Head from 'next/head'

const Header = (props) => {
    const router = useRouter()
    const title = props.title
    return (
        <>
            <Head>
                <title>{title} | Diamond GTA5RP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container">
                <div className={styles.header}>
                    <img src="img/logo.png" alt="" />
                    <div className={styles.nav}>
                        <Link href="/"><a className={ router.pathname === '/' ? styles.active :null} >Home</a></Link>
                        <Link href="/donate"><a className={ router.pathname === '/donate' ? styles.active :null}>Donate</a></Link>
                        <Link href="/rules"><a className={ router.pathname === '/rules' ? styles.active :null}>Rules</a></Link>
                        <Link href="/top"><a className={ router.pathname === '/top' ? styles.active :null}>Top</a></Link>
                    </div>
                    <div className={styles.btn}>Personal account</div>
                </div>
            </div>
            
        </>
    )
}
export default Header