import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Account() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Account | Diamond GTA5RP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}